### ISSUE TITLE
ERR_PNPM_FETCH_404

### ISSUE THREAD

**Issue by evanlong0926** [vant-ui/vant-nuxt#1]
```bash
pnpm add @vant/nuxt -D
```

GET https://registry.npmmirror.com/@vant%2Fnuxt: Not Found - 404

vant/nuxt is not in the npm registry, or you have no permission to fetch it.

**Comment by tolking** [comment]
Wait for the release of npm package

**Comment by chenjiahan** [comment]
@tolking I have released the initial `1.0.0-beta.0` version and sent you the invitation of `vant` npm org. 

So you can decide when to publish a stable version of `@vant/nuxt`. ^_^

**Comment by tolking** [comment]
ok👌
