### ISSUE TITLE
Error:can't import Layload on startup

### ISSUE THREAD

**Issue by QimiaoCloud** [vant-ui/vant-nuxt#10]
once the @vant/nuxt installed and run the Dev, the error occur:

ERROR  Failed to resolve import "vant/es/lazyload/Lazyload" from "virtual:nuxt:D:\projects\www.ok.ltd\.nuxt\components.client.mjs". 

could you help me?

**Comment by tolking** [comment]
version + config ?

**Comment by QimiaoCloud** [comment]
> version + config ?
d:\projects\www.ok.ltd>  npm ls --depth=0
www.ok.ltd@ D:\projects\www.ok.ltd
+-- @iconify/vue@4.1.1
+-- @nuxt/devtools@0.4.1
+-- @nuxtjs/color-mode@3.2.0
+-- @nuxtjs/device@3.1.0
+-- @types/marked@4.0.8
+-- @vant/nuxt@1.0.0
+-- marked@4.3.0
+-- mysql2@3.2.3
+-- nuxt-icon@0.3.3
+-- nuxt-simple-sitemap@2.4.11
+-- nuxt-svgo@1.2.1
+-- nuxt@3.4.2
`-- vant@4.2.0

**Comment by QimiaoCloud** [comment]
here is the nuxt.config.ts:

export default {
      modules: [
        '@vant/nuxt',
        '@nuxt/devtools',
        '@nuxtjs/color-mode',
        'nuxt-icon',
        // 'nuxt-svgo',
        'nuxt-simple-sitemap',
        '@nuxtjs/device',                
      ], 
      vant: {
       lazyload:false
      },           
      sitemap: {
        siteUrl: 'http://www.ok.ltd',
        exclude:["/playground/**"]
      },
      experimental:{
        // payloadExtraction:false,
        // componentIslands: true
      },
}


if I commented the @vant/nuxt ,it will be OK

**Comment by QimiaoCloud** [comment]
the vant-nuxt module version 1.0.0 is old and incompatible with Nuxt latest version 3.4.2. 


thank you so much!
