### ISSUE TITLE
vant 4 组件不支持SSR么？

### ISSUE THREAD

**Issue by AnyFork** [vant-ui/vant-nuxt#11]
采用vant-nuxt 和nuxt3 构建H5，发现大部分组件不支持SSR渲染，是不是不支持SSR?
![image](https://user-images.githubusercontent.com/49142023/233614780-e3a92095-ca1e-4292-93d0-2b3564bf743d.png)
![image](https://user-images.githubusercontent.com/49142023/233614834-6bde1bb8-606a-47bf-b884-0ab57d78f7f4.png)

**Comment by tolking** [comment]
Vant 是支持 SSR 的，欢迎你可以提供最小的复现demo

**Comment by AnyFork** [comment]
我用nuxt3测试了一下，tabs,list 组件不支持ssr

**Comment by tolking** [comment]
对于 Tabs： 你可以启用 :lazy-render="false"
List 似乎没有什么问题

如果需要更多的帮助，可以前往 Vant 仓库
