### ISSUE TITLE
van-image-preview

### ISSUE THREAD

**Issue by nideajun** [vant-ui/vant-nuxt#16]
van-image-preview v-model:show="show" :startPosition="index" transition="van-fade" :images="images"
    template #image="{ src }"
      img :src="src"/
    template
van-image-preview
  
  使用了vant-nuxt用这段代码只显示第一张图，鼠标左右拉都不动。我是在电脑上测试，但用plugin的方式自己写一个手工插件的方式就可以。注明已安装@vant/touch-emulator，而且我在调式的时候发现你们这个方式加载多少个组件就加载多少个css出来，这实在是太占连接了。应该弄成一个总的出来。否则人流量大的时候，服务器连接资源都被占光了。

**Comment by tolking** [comment]
无法复现

开发和生产版本的是不同的。生产版不会出现每个组件以单独的链接加载样式的情况

**Comment by nideajun** [comment]
你在电脑端的时候不要用手机防真模式，即普通模式就会拖不动图片了，用手机模式就可以。我用的是win11,edge浏览器。其它版本如下：
"@vant/nuxt": "^1.0.1",
    "nuxt": "^3.4.3",
    "vant": "^4.3.1"

**Comment by tolking** [comment]
vant 是面向手机端的组件库。这种特殊需求推荐你自己处理。

或者前往 vant 寻求更多帮助，该模块无法满足你的需求
