### ISSUE TITLE
nuxt3的vant中，生产环境样式错乱问题

### ISSUE THREAD

**Issue by Maxbsy** [vant-ui/vant-nuxt#19]
在该链接中能找到相似的问题，https://github.com/youzan/vant/issues/11049
但是目前解决方案是将按需引入改为全局引入。
那么nuxt3的vant中，是否有这个配置修改呢？

**Comment by tolking** [comment]
可以增加禁用样式加载的配置

**Comment by Maxbsy** [comment]
> 

是的，我是通过nuxt.config.ts的配置将按需引用排除掉，然后自行全局引用。但有没有更有效的方案呢？
