### ISSUE TITLE
How about move "vant" from the "devDependencies" to the "dependencies"?

### ISSUE THREAD

**Issue by BluesYoung-web** [vant-ui/vant-nuxt#25]
When i install this package by @nuxt/devtools, it will interrupt

![image](https://github.com/vant-ui/vant-nuxt/assets/55608642/0fbc093e-33b1-494e-8794-a855d2188ca8)

How about move "vant" from the "devDependencies" to the "dependencies", just like the @unocss/nuxt

![image](https://github.com/element-plus/element-plus-nuxt/assets/55608642/5e295410-c75b-4d8b-9d33-2a5db2408c0a)

**Comment by tolking** [comment]
Same with [Link](https://github.com/element-plus/element-plus-nuxt/issues/72).

Because this module will not be updated frequently. If write the Vant into dependencies, it is easy for user's project to reference different Vant, causing errors.
