### ISSUE TITLE
自动引入组件css分离后因加载顺序异常导致显示错误

### ISSUE THREAD

**Issue by DooperJ** [vant-ui/vant-nuxt#28]
包版本：
    nuxt:3.8.2
    Nitro:2.8.1
    Vant:4.8.0
    @vant/nuxt:1.0.4
问题：
    css文件顺序导致多个类名的元素css属性被覆盖
复现：
    问题暂时无法提供最小化情况复现，在nuxt dev时不存在该情况
    复现要求：
    1.项目总体积达到一点程度后
         会因为多两行行注释而异常，少两行注释则正常，也是无法提供最小化复现的原因
         猜测当总体积小于一定量的时候，vant的样式不会被拆分，会全部放在entry.css中
    2.需要通过nuxt build出来node运行
    3.受路由影响
        首页跳转到页面a，点击触发showImagePreview  =>  异常
        直接通过完整访问ssr的路由，点击触发showImagePreview  =>  正常
    4.影响组件包括但不限于showImagePreview、van-search
    上诉4点须同时满足，暂未确定其他影响因素

表现：
    异常表现：
![QQ截图20231208143054](https://github.com/vant-ui/vant-nuxt/assets/135101305/0059c48d-60b1-4b69-90ec-078963b23a61)
    期望/正常表现：
![QQ截图20231208143223](https://github.com/vant-ui/vant-nuxt/assets/135101305/7cafb790-84e6-475a-97b2-327f763f66ee)

暂时的解决方案：
    弃用@vant/nuxt，使用传统模式注册vant，如
/plugins/vant.js
`import vant from 'vant'
import 'vant/lib/index.css'

export default defineNuxtPlugin(nuxtApp => {
	nuxtApp.vueApp.use(vant)
})
`

**Comment by tolking** [comment]
[参考](https://github.com/youzan/vant/issues/11950)

你可以配置禁用样式自动加载，然后手动加载样式

```ts
modules: ['@vant/nuxt'],
  vant: {
    importStyle: false,
  },
```

**Comment by dostufffancy** [comment]
我也遇到了相似的问题，我是这样解决的
```javascript
vite: {
  build: {
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes("vant") && id.endsWith(".css")) {
            return "vant";
          }
        },
      },
    },
  },
}
```
