### ISSUE TITLE
全局方法如showToast不能给出正确的提示

### ISSUE THREAD

**Issue by decba78b** [vant-ui/vant-nuxt#31]
![image](https://github.com/vant-ui/vant-nuxt/assets/107607249/f1c03691-3769-405c-9cec-bf4905217c51)
![image](https://github.com/vant-ui/vant-nuxt/assets/107607249/099d75a4-be50-4129-ba1d-adbed8ac5e4a)
nuxt中的定义是来源于cjs的，尽管vant本身有dts
import.d.ts中的showToast为any类型，无法提供参数提示

**Comment by berial** [comment]
请问这个的解决方案是什么

**Comment by tolking** [comment]
参考 [#12944](https://github.com/youzan/vant/pull/12944) 

修改 `node_modules` -> `vant` -> `package.json`

删除 `.nuxt` 文件夹

重启应该就可以正常提示了

**Comment by decba78b** [comment]
> 请问这个的解决方案是什么

参考[#26830](https://github.com/nuxt/nuxt/issues/26830)，这个是有效的
