### ISSUE TITLE
How to configure browser adaptive effects for Vant4 combined with Nuxt3

### ISSUE THREAD

**Issue by zhenjameslee** [vant-ui/vant-nuxt#32]
The Nuxt3 official website does not have any relevant introduction.

**Comment by zhenjameslee** [comment]
尝试Vant4官网浏览器适配，但没效果，px依旧是px，根本就没有转成vw/vh

**Comment by tolking** [comment]
你可以看看 nuxt 文档，看看 postcss 应该怎么配置
