### ISSUE TITLE
Hydration node mismatch:

### ISSUE THREAD

**Issue by yuandaming** [vant-ui/vant-nuxt#34]
This error occurred when I used vant/list
<van-list>
        <van-cell v-for="item in state.list" :key="item.tid" :title="item.tid" />
</van-list>

package.json

"dependencies": {
    "autoprefixer": "^10.4.17",
    "nuxt": "^3.10.3",
    "pinia": "^2.1.7",
    "pinia-plugin-persist": "^1.0.0",
    "postcss": "^8.4.35",
    "vue": "^3.4.19",
    "vue-router": "^4.3.0",
    "weixin-js-sdk": "^1.6.5"
  },
  "devDependencies": {
    "@pinia/nuxt": "^0.5.1",
    "@vant/nuxt": "^1.0.4",
    "@vitejs/plugin-legacy": "^5.3.2",
    "postcss-pxtorem": "^6.1.0",
    "sass": "^1.71.1",
    "vant": "^4.9.1",
    "vite-plugin-svg-icons": "^2.0.1"
  },

**Comment by yuandaming** [comment]
<van-list>
        <van-cell v-for="item in state.list" :key="item.tid" :title="item.tid" />
    </van-list>

**Comment by yuandaming** [comment]
`<van-list>
        <van-cell v-for="item in state.list" :key="item.tid" :title="item.tid" />
    </van-list>`

**Comment by tolking** [comment]
[link](https://github.com/youzan/vant/pull/12719)
