### ISSUE TITLE
如何覆盖默认定制主题？

### ISSUE THREAD

**Issue by chenchenpp** [vant-ui/vant-nuxt#35]
![image](https://github.com/vant-ui/vant-nuxt/assets/33083284/56fc9f6a-e3b7-48a8-ac86-b0b8b1362175)
![image](https://github.com/vant-ui/vant-nuxt/assets/33083284/6869a786-bf40-4f02-9e61-cde5be7855a0)
![image](https://github.com/vant-ui/vant-nuxt/assets/33083284/c443b701-f3aa-4440-bead-74bad8f8f72b)

已经引入自定义配置，但是并不能覆盖默认主题，请问该如何配置？

**Comment by tolking** [comment]
可以尝试 `:root` -> `html`

**Comment by chenchenpp** [comment]
> 可以尝试 `:root` -> `html`

在html文件中维护:root？

**Comment by chenchenpp** [comment]
![image](https://github.com/vant-ui/vant-nuxt/assets/33083284/c3f98b5f-5b5b-4e8a-803d-5f482c8154b2)
已解决，vant官网提供了双root方式，可以提高优先级
