### ISSUE TITLE
暗黑模式下 Vant 组件发生闪烁

### ISSUE THREAD

**Issue by CharleeWa** [vant-ui/vant-nuxt#43]
@tolking 作者，您好！我在使用这个模块时遇到这样一个问题：暗黑模式背景下，vant 组件会发生短暂的闪烁。我的业务组件使用 @nuxtjs/color-mode 实现暗黑，而 vant 通过 VanConfigProvider 组件提供全局的暗黑支持。我曾使用 color-mode 的 [ColorScheme ](https://color-mode.nuxtjs.org/#caveats) 组件避免闪烁，但这个组件的实现背后是客户端渲染，这等于放弃了SSR。我发现 van-theme-dark 类是延迟了一会再加到 html class 上的，这可能是问题所在。是不是我哪里配置的不对？如果您能给一些建议就太好了，谢谢啦！仓库地址：https://github.com/easy-temps/nuxt-vant-mobile

**Comment by tolking** [comment]
你可以检查一下两者对应的节点和类名是否一致

**Comment by CharleeWa** [comment]
> 你可以检查一下两者对应的节点和类名是否一致

分别是 dark 和 van-theme-dark 两个不同的类名

**Comment by CharleeWa** [comment]
我是这样解决的。

```ts
// 1、utils/preload.ts
export default function preload() {
  return `
    ;(function() {
      const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
      const setting = localStorage.getItem('nuxt-color-mode') || 'auto';
      if (setting === 'dark' || (prefersDark && setting !== 'light'))
        document.documentElement.classList.toggle('van-theme-dark', true);
    })()
  `
}

// 2、nuxt.config.ts

 app: {
    head: {
      script: [
        { innerHTML: preload(), type: 'text/javascript', tagPosition: 'head' },
      ],
    },
  },
```
