### ISSUE TITLE
有没有基于vue2版本的版本

### ISSUE THREAD

**Issue by pengyuan-max** [vant-ui/vant-nuxt#6]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/31642027/222395312-1c63d0a4-59db-42cb-b355-7fea724c25f8.png">

**Comment by tolking** [comment]
nuxt2 和 nuxt3 的 api 存在着差异，可能暂时无法提供 nuxt2 的版本。

**Comment by nideajun** [comment]
能不能在导入css的时候不要放在页面里，只导那个外部css就可以了，我发现你们<style>里一堆。后面还有一个外链的inde随机码.css文件,这个文件的内容跟style里那一堆是重复的。我只想要后面这个外链文件，有什么参数可以设定吗？我用了vant: {
    /** Options */
    importStyle:false
  },两个都会消失。

**Comment by tolking** [comment]
可以选择取消行内样式

```ts
export default defineNuxtConfig({
  modules: [ElementPlus],
  experimental: { inlineSSRStyles: false },
})
```

**Comment by nideajun** [comment]
可以了，谢谢哇，你太牛了！
&nbsp;


浪箭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月18日(星期一) 晚上6:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vant-ui/vant-nuxt] 有没有基于vue2版本的版本 (Issue #6)





 
可以选择取消行内样式
 export default defineNuxtConfig({   modules: [ElementPlus],   experimental: { inlineSSRStyles: false }, })

**Comment by tolking** [comment]
当前的方式没有办法应用于Nuxt2 和 Nuxt-Bridge，抱歉无法支持 vue2
