### ISSUE TITLE
nuxt3中修改srcDir属性为'/src'后使用vant组件类型声明找不到

### ISSUE THREAD

**Issue by daomiaru** [vant-ui/vant-nuxt#9]
nuxt3中使用vant
![image](https://user-images.githubusercontent.com/52020723/232672625-5631d2f0-dc15-4b5b-a81f-1a9aaa6c3433.png)
![image](https://user-images.githubusercontent.com/52020723/232672707-04138f8d-f998-4141-8f03-42428f3c6b20.png)
将vant类型声明文件修改后可用，但保存后项目会自动改为vue
![image](https://user-images.githubusercontent.com/52020723/232672833-d252abbb-a6ea-4f23-8c15-e88b4199e7f9.png)
![image](https://user-images.githubusercontent.com/52020723/232672966-921ba9ad-8868-459f-9cd1-8e70afbbcbbc.png)
如何解决

**Comment by tolking** [comment]
组件类型是有 nuxt 自动生成的。

我看你 `src` 目录下存在 components.d.ts 和 vant.d.ts ，这两者可能存在冲突，你可以选择移除 src 目录下的文件

**Comment by daomiaru** [comment]
> 

van.d.ts是我测试用自己写的文件，尝试移除了也不行

**Comment by daomiaru** [comment]
> 组件类型是有 nuxt 自动生成的。
> 
> 我看你 `src` 目录下存在 components.d.ts 和 vant.d.ts ，这两者可能存在冲突，你可以选择移除 src 目录下的文件

**Comment by tolking** [comment]
包括 src/components.d.ts 文件。

**Comment by daomiaru** [comment]
> 包括 src/components.d.ts 文件。

明白，我这边把自动生成的类型声明文件都删了，只保留.nuxt中的类型声明，的确解决了这个问题。问题的来源定位了一下就是这两份代码之间有冲突
![image](https://user-images.githubusercontent.com/52020723/232945510-2dcfc642-7f66-4e09-99f7-27dcf23ce517.png)
如何处理这种问题呢

**Comment by tolking** [comment]
你的问题与本仓库无关，unplugin-vue-components 并不推荐在 nuxt中使用。

据我所知目前并没有相关配置的api，你需要前往对应仓库寻求帮助
